version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: placetogrow_laravel
    ports:
      - "8000:8000"
    volumes:
      - .:/app/z
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: placetogrow_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: placetogrow
      MYSQL_ROOT_PASSWORD: placetogrow123Root*

  nginx:
    image: nginx:alpine
    container_name: placetogrow_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/app
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - app
      - mysql

volumes:
  mysql-data:
