name: PlaceToGrow

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ["8.2"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extension: json, dom, curl, libxml, mbstring
          coverage: xdebug

      - name: Check PHP
        run: php -v

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Use SQLite for testing
        run: |
          cp .env .env.testing
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/' .env.testing
          sed -i 's/DB_HOST=127.0.0.1/# DB_HOST=127.0.0.1/' .env.testing
          sed -i 's/DB_PORT=3306/# DB_PORT=3306/' .env.testing
          sed -i 's/DB_DATABASE=laravel/# DB_DATABASE=laravel/' .env.testing
          sed -i 's/DB_USERNAME=root/# DB_USERNAME=root/' .env.testing
          sed -i 's/DB_PASSWORD=root/# DB_PASSWORD=root/' .env.testing

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Generate application key
        run: php artisan key:generate --force

      - name: Show application key
        run: grep APP_KEY .env.testing

      - name: Run migrations for SQLite
        run: php artisan migrate --force --env=testing

      - name: Run tests with phpunit/phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
