name: PlaceToGrow

on:
  push:
    branches: [feature/marco/actions]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ["8.2"]

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extension: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Check PHP
        run: php -v

      - uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run npm install
        run: npm install

      - name: Run test
        run: php artisan test
